name: Notify Discord on Push

on:
  push:
    branches:
      - main # 或你想监听的分支

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          commit_message=$(git log -1 --pretty=format:"%s")
          payload="{
            \"content\": \"仓库有新推送！\\n提交信息：$commit_message \\n作者：${{ github.actor }}\\n[查看详情](${{ github.event.compare }})\"
          }"
          curl -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK
